# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "yourName": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://CailleauThierry.github.io/tcai_nbdev_tutorial/"

git_url = "https://github.com/CailleauThierry/tcai_nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
