# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'yourName']

# Cell
def  say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
say_hello("Sylvain")

# Cell
from IPython.display import display,SVG
display(SVG('<svg height="100"><circle cx="50" cy="50" r="40"/></svg>'))

# Cell
assert say_hello("Jeremy")=="Hello Jeremy!"

# Cell
yourName = input()
print()
#the previous print() is only to workaround AN nbdev_build_docs/jupyter input() bug
print("Hello", yourName)
print("Hello", yourName , "Welcome!")